# Generated by Django 5.0 on 2024-01-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                ("email", models.EmailField(max_length=100)),
                ("age", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
