# Generated by Django 5.0 on 2024-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
