# Generated by Django 5.0 on 2024-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_appeal_name_alter_appeal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='description',
        ),
        migrations.AddField(
            model_name='appeal',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
