# Generated by Django 5.0 on 2024-01-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_appeal_description_appeal_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='info',
            new_name='text_data',
        ),
    ]
