version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./web-service:/server
      - ./data/web:/vol/web
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    command: ["bash",
              "-c",
              "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"]
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - django

volumes:
  postgres-data: