# Generated by Django 5.0 on 2024-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(default=False),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
