# Generated by Django 5.0 on 2023-12-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                ("email", models.EmailField(max_length=100)),
                ("username", models.CharField(max_length=500, verbose_name="Имя")),
                ("age", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
